
# enable app support
APP=1
APP_STACKSIZE=300

VPATH += src/
PROJ_OBJ += hello_world.o

PROJ_OBJ += pos_localization.o
INCLUDES += -Iinterface/

CRAZYFLIE_BASE=../..
include $(CRAZYFLIE_BASE)/Makefile